name = "squiggleconf-com"
main = "./dist/_worker.js/index.js"
compatibility_date = "2026-07-25"
compatibility_flags = ["nodejs_compat"]
preview_urls = true

[[routes]]  
pattern = "squiggleconf.com"
custom_domain = true

[vars]
BREVO_LIST_ID = "3"

[assets]
binding = "ASSETS"
directory = "./dist"
